/**
 * DOCX report — same content as PDF report.
 */
import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  ShadingType,
  Footer,
  PageNumber
} from 'docx'
import type { ReportData, ReportFinding } from './report-data'
import type { Severity } from '@shared/types/knowledge'

const SEVERITY_HEX: Record<Severity, string> = {
  critical: 'DC2626',
  high: 'EA580C',
  medium: 'CA8A04',
  low: '2563EB',
  informational: '64748B'
}

const ACCENT = '6366F1'

export async function generateDocxReport(data: ReportData): Promise<ArrayBuffer> {
  const children: (Paragraph | Table)[] = []

  // Title
  children.push(
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: 'AI Threat Model Report', bold: true })]
    })
  )
  children.push(
    new Paragraph({
      children: [new TextRun({ text: data.project.name, size: 28, color: '64748B' })]
    })
  )
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: `Generated: ${formatDate(data.generatedAt)}`, size: 18, color: '64748B' })
      ]
    })
  )
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Tool: ${data.appName} v${data.appVersion}`,
          size: 18,
          color: '64748B'
        })
      ]
    })
  )

  if (data.project.description) {
    children.push(new Paragraph({ text: '' }))
    children.push(new Paragraph({ children: [new TextRun({ text: data.project.description })] }))
  }

  // Executive Summary
  children.push(heading('Executive Summary'))
  children.push(
    new Paragraph({
      children: [
        new TextRun({ text: `Components modeled: ${data.project.componentCount}`, break: 1 }),
        new TextRun({ text: `Data flows modeled: ${data.project.flowCount}`, break: 1 }),
        new TextRun({ text: `Trust boundaries: ${data.project.boundaryCount}`, break: 1 }),
        new TextRun({ text: `Total findings: ${data.summary.total}`, break: 1 })
      ]
    })
  )

  // Severity table
  children.push(new Paragraph({ text: '' }))
  children.push(
    table(
      ['Severity', 'Count'],
      (['critical', 'high', 'medium', 'low', 'informational'] as Severity[]).map((s) => [
        s.toUpperCase(),
        String(data.summary.bySeverity[s])
      ])
    )
  )

  // Components
  children.push(heading('Components'))
  children.push(
    table(
      ['Label', 'Type', 'Classification'],
      data.components.map((c) => [c.label, c.type, c.classification ?? '—'])
    )
  )

  // Data flows
  children.push(heading('Data Flows'))
  children.push(
    table(
      ['Label', 'Source', 'Target', 'Encrypted', 'Authenticated', 'Classification'],
      data.flows.map((f) => [
        f.label,
        f.source,
        f.target,
        f.encrypted ? 'Yes' : 'No',
        f.authenticated ? 'Yes' : 'No',
        f.classification
      ])
    )
  )

  // Boundaries
  if (data.boundaries.length > 0) {
    children.push(heading('Trust Boundaries'))
    children.push(
      table(
        ['Label', 'Type', 'Components'],
        data.boundaries.map((b) => [b.label, b.type, String(b.nodeCount)])
      )
    )
  }

  // Findings
  children.push(heading('Findings'))
  if (data.findings.length === 0) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'No findings produced by current analysis.', italics: true, color: '64748B' })
        ]
      })
    )
  } else {
    for (const f of data.findings) {
      children.push(...renderFinding(f))
    }
  }

  // Notes
  if (data.notes.length > 0) {
    children.push(heading('Notes & Assumptions'))
    children.push(
      table(
        ['Category', 'Note'],
        data.notes.map((n) => [n.category, n.content])
      )
    )
  }

  const doc = new Document({
    creator: data.author,
    title: `AI Threat Model — ${data.project.name}`,
    description: `Generated by ${data.appName} v${data.appVersion}`,
    sections: [
      {
        children,
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: `${data.appName} v${data.appVersion} — Page `,
                    size: 16,
                    color: '64748B'
                  }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '64748B' }),
                  new TextRun({ text: ' of ', size: 16, color: '64748B' }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: '64748B' })
                ]
              })
            ]
          })
        }
      }
    ]
  })

  const blob = await Packer.toBlob(doc)
  return await blob.arrayBuffer()
}

function heading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 320, after: 120 },
    children: [new TextRun({ text, bold: true, color: ACCENT })]
  })
}

function renderFinding(f: ReportFinding): Paragraph[] {
  const sevColor = SEVERITY_HEX[f.severity]
  const out: Paragraph[] = []

  out.push(
    new Paragraph({
      spacing: { before: 240, after: 80 },
      children: [
        new TextRun({
          text: ` ${f.severity.toUpperCase()} `,
          bold: true,
          color: 'FFFFFF',
          shading: { type: ShadingType.SOLID, color: sevColor, fill: sevColor }
        }),
        new TextRun({ text: '  ' }),
        new TextRun({ text: f.title, bold: true, size: 24 }),
        new TextRun({ text: `   ${f.ruleId}`, size: 16, color: '64748B' })
      ]
    })
  )

  out.push(new Paragraph({ children: [new TextRun({ text: f.description })] }))

  out.push(
    new Paragraph({
      children: [
        new TextRun({ text: 'Rationale: ', bold: true, italics: true, color: '64748B' }),
        new TextRun({ text: f.rationale, italics: true, color: '64748B' })
      ]
    })
  )

  if (f.affectedComponents.length > 0) {
    out.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Affected components: ', bold: true }),
          new TextRun({ text: f.affectedComponents.join(', ') })
        ]
      })
    )
  }

  if (f.frameworks.length > 0) {
    out.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Frameworks: ', bold: true, color: ACCENT }),
          new TextRun({ text: f.frameworks.join('  |  '), color: ACCENT })
        ]
      })
    )
  }

  if (f.mitigations.length > 0) {
    out.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Mitigations: ', bold: true }),
          new TextRun({ text: f.mitigations.join('; ') })
        ]
      })
    )
  }

  out.push(
    new Paragraph({
      spacing: { after: 120 },
      children: [
        new TextRun({ text: 'Recommendation: ', bold: true }),
        new TextRun({ text: f.recommendation })
      ]
    })
  )

  return out
}

function table(headers: string[], rows: string[][]): Table {
  const border = {
    top: { style: BorderStyle.SINGLE, size: 4, color: 'CBD5E1' },
    bottom: { style: BorderStyle.SINGLE, size: 4, color: 'CBD5E1' },
    left: { style: BorderStyle.SINGLE, size: 4, color: 'CBD5E1' },
    right: { style: BorderStyle.SINGLE, size: 4, color: 'CBD5E1' }
  }

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        tableHeader: true,
        children: headers.map(
          (h) =>
            new TableCell({
              shading: { type: ShadingType.SOLID, color: ACCENT, fill: ACCENT },
              children: [
                new Paragraph({
                  children: [new TextRun({ text: h, bold: true, color: 'FFFFFF', size: 18 })]
                })
              ]
            })
        )
      }),
      ...rows.map(
        (row) =>
          new TableRow({
            children: row.map(
              (cell) =>
                new TableCell({
                  children: [new Paragraph({ children: [new TextRun({ text: cell, size: 18 })] })]
                })
            )
          })
      )
    ],
    borders: {
      top: border.top,
      bottom: border.bottom,
      left: border.left,
      right: border.right,
      insideHorizontal: { style: BorderStyle.SINGLE, size: 2, color: 'E2E8F0' },
      insideVertical: { style: BorderStyle.SINGLE, size: 2, color: 'E2E8F0' }
    }
  })
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString()
  } catch {
    return iso
  }
}
